version: '3.9'
services:
  # Backend service
  backend:
    container_name: amazon-order-service-backend
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    ports:
      - ${APP_FORWARD_PORT:-8081}:${APP_PORT:-8081}
    volumes:
      - .:/app
    networks:
      - amazon-order-service_shared_network
    restart: on-failure
    tty: true
    stdin_open: true
    expose:
      - ${APP_PORT:-8081}
networks:
  amazon-order-service_shared_network:
    name: amazon-order-service_shared_network
    external: true
#docker network create amazon-order-service-shared-network
